pipeline:
  identifier: Build_Python_Project_1736338149059
  name: Build Python_Project
  orgIdentifier: default
  projectIdentifier: Manish
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: manishrepo
        repoName: Python_Project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: pip install -r requirements.txt
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: python run.py
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              container:
                image: python:3.9
        type: CI
